"""metrics table

Revision ID: af293fe22067
Revises: adfd14a2c576
Create Date: 2020-08-31 19:23:11.403340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af293fe22067'
down_revision = 'adfd14a2c576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=True),
    sa.Column('service_element_name', sa.String(length=120), nullable=True),
    sa.Column('service_level_detail', sa.Text(), nullable=True),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('service_provider_steward_1', sa.String(length=120), nullable=True),
    sa.Column('metric_name', sa.String(length=120), nullable=True),
    sa.Column('metric_description', sa.Text(), nullable=True),
    sa.Column('metric_rationale', sa.Text(), nullable=True),
    sa.Column('metric_value_display_format', sa.String(length=120), nullable=True),
    sa.Column('threshold_target', sa.Integer(), nullable=True),
    sa.Column('threshold_target_rationale', sa.String(length=500), nullable=True),
    sa.Column('threshold_target_direction', sa.String(length=10), nullable=True),
    sa.Column('threshold_trigger', sa.Integer(), nullable=True),
    sa.Column('threshold_trigger_rationale', sa.String(length=500), nullable=True),
    sa.Column('threshold_trigger_direction', sa.String(length=10), nullable=True),
    sa.Column('data_source', sa.String(length=120), nullable=True),
    sa.Column('data_update_frequency', sa.String(length=120), nullable=True),
    sa.Column('metric_owner_primary', sa.String(length=120), nullable=True),
    sa.Column('vantage_control_id', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_data_source'), 'metric', ['data_source'], unique=False)
    op.create_index(op.f('ix_metric_data_update_frequency'), 'metric', ['data_update_frequency'], unique=False)
    op.create_index(op.f('ix_metric_metric_name'), 'metric', ['metric_name'], unique=False)
    op.create_index(op.f('ix_metric_metric_owner_primary'), 'metric', ['metric_owner_primary'], unique=False)
    op.create_index(op.f('ix_metric_service_element_name'), 'metric', ['service_element_name'], unique=False)
    op.create_index(op.f('ix_metric_service_name'), 'metric', ['service_name'], unique=False)
    op.create_index(op.f('ix_metric_service_provider_steward_1'), 'metric', ['service_provider_steward_1'], unique=False)
    op.create_index(op.f('ix_metric_target'), 'metric', ['target'], unique=False)
    op.create_index(op.f('ix_metric_vantage_control_id'), 'metric', ['vantage_control_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_vantage_control_id'), table_name='metric')
    op.drop_index(op.f('ix_metric_target'), table_name='metric')
    op.drop_index(op.f('ix_metric_service_provider_steward_1'), table_name='metric')
    op.drop_index(op.f('ix_metric_service_name'), table_name='metric')
    op.drop_index(op.f('ix_metric_service_element_name'), table_name='metric')
    op.drop_index(op.f('ix_metric_metric_owner_primary'), table_name='metric')
    op.drop_index(op.f('ix_metric_metric_name'), table_name='metric')
    op.drop_index(op.f('ix_metric_data_update_frequency'), table_name='metric')
    op.drop_index(op.f('ix_metric_data_source'), table_name='metric')
    op.drop_table('metric')
    # ### end Alembic commands ###
